[supervisord]
nodaemon=true

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1280x720x24
autorestart=true
priority=1

[program:xfce]
environment=DISPLAY=":1"
command=/usr/bin/startxfce4
autorestart=true
priority=2

[program:vnc]
command=/usr/bin/x11vnc -display :1 -forever -shared -nopw -rfbport 5900 -noxdamage -repeat -xkb
autorestart=true
priority=3

[program:ssh]
command=/usr/sbin/sshd -D
autorestart=true
priority=4

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc 8080 localhost:5900
autorestart=true
priority=5
