[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1280x720x24 -ac +extension GLX +render -noreset
priority=10
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:xfce]
command=/usr/bin/startxfce4
environment=DISPLAY=":1",HOME="/root"
priority=20
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -forever -shared -nopw -listen 0.0.0.0 -rfbport 5900 -noxdamage -repeat -xkb
priority=30
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:websockify]
command=/usr/bin/websockify --web=/usr/share/novnc 8080 localhost:5900
priority=40
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:sshd]
command=/usr/sbin/sshd -D
priority=50
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
