[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:xvfb]
command=/start-xvfb.sh
priority=10
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:xfce]
command=/start-xfce.sh
priority=20
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
environment=DISPLAY=":1",HOME="/root"

[program:vnc]
command=/start-vnc.sh
priority=30
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:novnc]
command=/start-novnc.sh
priority=40
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:sshd]
command=/usr/sbin/sshd -D
priority=50
autostart=true
autorestart=true
startsecs=2
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
